CREATE TABLE user(
user_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR(45) NOT NULL,
first_name VARCHAR(45) NOT NULL,
last_name VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL,
PRIMARY KEY (user_id)
);

CREATE TABLE item(
item_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
quantity INT UNSIGNED NOT NULL,
price INT UNSIGNED NOT NULL,
status ENUM('sold out', 'available'),
PRIMARY KEY (item_id)
);

CREATE TABLE orders(
order_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL,
item_id INT UNSIGNED NOT NULL,
price INT UNSIGNED NOT NULL,
PRIMARY KEY (order_id),
CONSTRAINT user_orders FOREIGN KEY(user_id)
REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT orders_item FOREIGN KEY(item_id)
REFERENCES item(item_id) ON DELETE CASCADE ON UPDATE CASCADE
);